#ifndef _SKYLOFT_UAPI_DEV_H_
#define _SKYLOFT_UAPI_DEV_H_

#define SKYLOFT_IO_BASE               0x1000
#define SKYLOFT_IO_PARK               _IO(SKYLOFT_IO_BASE, 1)
#define SKYLOFT_IO_WAKEUP             _IO(SKYLOFT_IO_BASE, 2)
#define SKYLOFT_IO_SWITCH_TO          _IO(SKYLOFT_IO_BASE, 3)
#define SKYLOFT_IO_SETUP_DEVICE_UINTR _IO(SKYLOFT_IO_BASE, 4)
#define SKYLOFT_IO_TIMER_SET_HZ       _IO(SKYLOFT_IO_BASE, 5)
#define SKYLOFT_IO_IPI_SEND           _IO(SKYLOFT_IO_BASE, 6)
#define SKYLOFT_IO_IPI_BENCH          _IO(SKYLOFT_IO_BASE, 7)

#define SKYLOFT_SETUP_DEVICE_UINTR_FLAGS_TIMER 0x1

#define SKYLOFT_DEV_NAME "skyloft"
#define SKYLOFT_DEV_PATH "/dev/" SKYLOFT_DEV_NAME

#endif // _SKYLOFT_UAPI_DEV_H_
